//user
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//search
export const GET_SEARCH = 'GET_SEARCH';
export const SEARCH_LOADING = 'SEARCH_LOADING';

//mysearches
export const GET_SEARCHES = 'GET_SEARCHES';
export const ADD_SEARCH = 'ADD_SEARCH';
export const DELETE_SEARCH = 'DELETE_SEARCH';
export const SEARCHES_LOADING = 'SEARCHES_LOADING';
export const IS_QUICK_SEARCH = 'IS_QUICK_SEARCH';
export const QUICK_SEARCH_ID = 'QUICK_SEARCH_ID';

//preferences
export const CREATE_PREFERENCES = 'CREATE_PREFERENCES';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const PREFERENCES_LOADING = 'PREFERENCES_LOADING';

//comments
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const GET_COMMENT = 'GET_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const COMMENT_LOADING = 'COMMENT_LOADING';